version: "3.3"

services:
  frontend:
    build: .
    restart: always
    volumes:
      - valami:/usr/share/nginx/html/
    ports:
      - 5000:80
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: db

volumes:
  valami: